### ISSUE TITLE
Bugs new Update

### ISSUE THREAD

**Issue by RizzooTv** [VORPCORE/VORP-Character#22] opened 2022-03-26 03:43 UTC
https://prnt.sc/UifWHQn3AckE
Creating a new character is not possible, nothing is displayed, gender selection is not possible

---------------

https://prnt.sc/OV6SCdeuEB7r  ,  https://prnt.sc/MjqzDA1gxp76
Spwan, in the character selection window, the char has no clothes on, but has hair! Then when you spawt, he has clothes on but his hair is gone.

--------------
https://prnt.sc/r8CM_EBxIOa1
Character deletion is not possible

-------------

Character Reload causes heart damage

**Comment by outsider31000** [comment] 2022-03-26 08:15
Thanks for reporting  use the one from premade server  for the meantime pls.

**Comment by Local9** [comment] 2022-03-26 10:44
First issue has been fixed in the latest pull request, but not in the build folder, will be killing off that folder soon.
Second issue is something I've been looking at, and its a weird issue, shouldn't be happening, but is.
Third one I'll look into, this was a prompt system that Blue sent me that he wanted added.

**Comment by Local9** [comment] 2022-03-26 11:41
First issue was fixed in https://github.com/VORPCORE/VORP-Character/pull/21
Third and Forth issue is now fixed in https://github.com/VORPCORE/VORP-Character/pull/23

Second issue I'll be looking into while at work

**Comment by Local9** [comment] 2022-03-26 11:48
Release https://github.com/VORPCORE/VORP-Character/releases/tag/v1.0.1 covers the fixes

**Comment by RizzooTv** [comment] 2022-03-26 17:58
Creating and deleting characters now works fine!
In the character selection and when spawening, however, the charater has no clothes on, only after a character reload

**Comment by Local9** [comment] 2022-03-26 18:30
I've just released a new hotfix for character deletion/creation when a user joins with no characters, so please do use that one.

As for the character selection, and no clothes, I'm currently investigating it.

**Comment by Local9** [comment] 2022-03-26 20:01
Please try the latest release; https://github.com/VORPCORE/VORP-Character/releases/tag/v1.0.1-hotfix.3

**Comment by RizzooTv** [comment] 2022-03-26 20:58
In the character selection you now have clothes again, so wonderful :D

Not at spawn, however, and the delete character window no longer closes after deleting.

**Comment by Hailey-Ross** [comment] 2022-03-28 17:00
I am also having the same issues with the latest vorp_characters release.

Characters are spawning with no clothes on and have to /rc

Deleting characters, the window does not close properly.

**Comment by Local9** [comment] 2022-03-28 19:10
Please try; https://github.com/VORPCORE/VORP-Character/releases/tag/v1.0.1-hotfix.4

**Comment by RizzooTv** [comment] 2022-03-28 19:31
It works very well now,Thanks alot

**Comment by Hailey-Ross** [comment] 2022-03-29 02:41
Works well, Players still don't have hair on login or when changing clothes but a quick /rc and its back.

**Comment by Hailey-Ross** [comment] 2022-03-29 03:00
Also has an issue where female characters are completely naked during and after character creation. Have not tested Male characters yet but the male model on the main selection screen had pants on.

Also after trying to change clothes in the Clothes store on the newly created character, the female character put on the hat I chose but nothing else stuck and even /rc does not update to the changed clothes.

Tried going to the changing room but choosing the saved outfit did not load any differently to how the store functioned.

**Comment by Hailey-Ross** [comment] 2022-03-29 04:09
After moving back to a previous version of Vorp_Character the user that was created on the newer version loads correctly and has their clothes saved properly.

**Comment by Local9** [comment] 2022-03-29 11:47
Ok, for now, stick with the version that works for you as I want to put all my efforts into the complete refactor.

**Comment by Local9** [comment] 2022-04-02 14:20
Closing this one as the issue is now mostly related to the characters body being incorrectly refreshed. https://github.com/VORPCORE/VORP-Character/issues/29

**Closed by Local9** 2022-04-02 14:20 UTC
Labels: bug, enhancement, research
